config/routes.rb
Rails.application.routes.draw do
  resources :signs

  resources :employees

  get '/generat_payroll' => 'employees#generat_payroll'
  post '/payroll' => 'employees#payroll'
  get '/payrollxls' => 'employees#payrollxls'
  get '/new_sign' => 'employees#new_sign'
  get '/SmartSign' => 'employees#new_sign'
  post '/check' => 'employees#check'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :signs
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |employee|
        csv << employee.attributes.values_at(*column_names)
      end
    end
  end
  
  def full_name 
     "#{first_name} #{last_name}"
  end
  
  def working_hours(start_date, end_date)
    puts "=============================="
    puts "the start and end are #{start_date.inspect} and end is #{end_date.inspect}"
    puts "==================================="
    total_hours = 0
    salary = 0
      signs.each do |sign|
        if sign.date > start_date && sign.date < end_date
          total_hours = total_hours + (sign.check_out - sign.check_in) / 3600.0
        end 
      end
    salary = total_hours * pay_rate
    return [total_hours, salary]
  end
  
# check the status of todays sign in or out
# if not signed in -> sign_in
# if signed_in -> sign_out

  def check_today_sign
    status = 0
    
    if signs.last.check_out != nil
      status = 0
    else 
      status = 1
    end
    return status
  end
  
#end class
end

app/models/sign.rb
class Sign < ActiveRecord::Base
  belongs_to :emplyee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  #GET /generate_payroll
  def generat_payroll  
  end
  
  
  
  def payroll
     @from = Date.new(params["report"]["from(1i)"].to_i, params["report"]["from(2i)"].to_i, params["report"]["from(3i)"].to_i)
    @to = Date.new(params["report"]["to(1i)"].to_i, params["report"]["to(2i)"].to_i, params["report"]["to(3i)"].to_i)
    @employees = Employee.all
  end
  
  def payrollxls
    @employees = Employee.all
    respond_to do |format|
      format.html
      format.csv { send_data @employees.to_csv }
      format.xls 
    end
  end
  
  
  def new_sign
  end
  
  def check
    @employee = Employee.find(params["employee"]["id"])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :pay_rate, :signs)
    end

#end class
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  before_action :set_sign, only: [:show, :edit, :update, :destroy]

  # GET /signs
  # GET /signs.json
  def index
    @signs = Sign.all
  end

  # GET /signs/1
  # GET /signs/1.json
  def show
  end

  # GET /signs/new
  def new
    @sign = Sign.new
  end

  # GET /signs/1/edit
  def edit
  end

  # POST /signs
  # POST /signs.json
  def create
    @sign = Sign.new(sign_params)

    respond_to do |format|
      if @sign.save
        format.html { redirect_to @sign, notice: 'Sign was successfully created.' }
        format.json { render :show, status: :created, location: @sign }
      else
        format.html { render :new }
        format.json { render json: @sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signs/1
  # PATCH/PUT /signs/1.json
  def update
    respond_to do |format|
      if @sign.update(sign_params)
        format.html { redirect_to @sign, notice: 'Sign was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign }
      else
        format.html { render :edit }
        format.json { render json: @sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signs/1
  # DELETE /signs/1.json
  def destroy
    @sign.destroy
    respond_to do |format|
      format.html { redirect_to signs_url, notice: 'Sign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign
      @sign = Sign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_params
      params.require(:sign).permit(:employee_id, :date, :check_in, :check_out)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/signs_helper.rb
module SignsHelper
end

app/views/employees/_check_in.html.erb
<div class="center">
<%= form_for(sign) do |f| %>
  <% if sign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sign.errors.count, "error") %> prohibited this sign from being saved:</h2>

      <ul>
      <% sign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :employee_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :date %>
  </div>
  
  <div class="field">
    <%= f.label :check_in %><br>
    <%= f.time_select("check_in", ampm: true) %>
  </div>
  
  <br>
  <div class="actions">
    <%= f.submit "Check in"%>
  </div>
<% end %>
</div>

app/views/employees/_check_out.html.erb
<div class="center">
<%= form_for(sign) do |f| %>
  <% if sign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sign.errors.count, "error") %> prohibited this sign from being saved:</h2>

      <ul>
      <% sign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :employee_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :date %>
  </div>
  <div class="field">
    <%= f.hidden_field :check_in %>
  </div>
  
  <div class="field">
    <%= f.label :check_out %><br>
    <%= f.time_select("check_out", ampm: true) %>
  </div>
  
  <br>
  <div class="actions">
    <%= f.submit "check out"%>
  </div>
<% end %>
</div>

app/views/employees/_form_check.html.erb
<h1>  Please select your name, then press check. </h1>

<%= form_tag(:action => 'check') do %>
<p>
 <%# select("employee", "id", Employee.all.collect {|e| [e.full_name, e.id] }, {include_blank: true}) %>
  <%= select("employee", "id", Employee.order("first_name").collect {|e| [e.full_name, e.id] }, {include_blank: true}) %>
</p>
<p>
  <%= submit_tag("check") %>
</p>  
<% end %>

app/views/employees/_sign_list.html.erb
<h1>Listing signs</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Check in</th>
      <th>Check out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% signs.each do |sign| %>
      <tr>
        <td><%= sign.date %></td>
        <td><%= sign.check_in.strftime("%I:%M %p") %></td>
        <td><%= sign.check_out.strftime("%I:%M %p") %></td>
        <td><%= link_to 'Show', sign %></td>
        <td><%= link_to 'Edit', edit_sign_path(employee.sign.last) %></td>
        <td><%= link_to 'Destroy', sign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign', new_sign_path %>

app/views/employees/check.html.erb
<div class="center">
  <h1> Date: <%= Time.now.strftime("%m-%d-%y ")%> </h1>
    <% status = @employee.check_today_sign %>
 
  <% if status == 0 %>
  
  <h1> Al Salam Alikom <%= @employee.full_name %> , please sign in. </h1>

    <%= render :partial => "check_in", :locals =>{:sign => Sign.new( :employee_id => @employee.id, :date => Date.today)} %>
 
  
  <% else %>
  <h1>Jazakom Allah Khayran <%= @employee.full_name %>, please sign out </h1>
  
  <%= render :partial => "check_out", :locals =>{:sign => @employee.signs.last} %>
  
  <% end %>
</div>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/generat_payroll.html.erb
<h1>Listing employees working hours for the period: </h1>

<%= form_tag(:action => 'payroll') do %>
<p>
From: <%= date_select("report", "from")%>
</p>
<p>
To   :   <%= date_select("report", "to") %>
</p>
<p>
<%= submit_tag("Report") %>
</p>
<% end %>

app/views/employees/index.html.erb
<div class="center">
<h1>Listing employees</h1>
  
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Pay rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.pay_rate %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>
</div>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/new_sign.html.erb
<h1>Al Salam Alikom</h1>
<h1>Date: <%= Date.today%></h1>

<%= render 'form_check' %>

app/views/employees/payroll.html.erb
<h1>Employees working hours for the period from <%= @from%> to <%= @to%></h1>
<p>
  Download:
  <%= link_to "CSV", employees_path(format: "csv") %> |
  <%= link_to "Excel", payrollxls_path(format: "xls", :locals =>{:from => @from, :to => @to})%>

</p>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Working hours</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <% x = employee.working_hours( @from, @to )%>
        <td><%= x[0] %></td>
        <td><%= x[1] %></td>
        
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/payrollxls.xls.erb
<h1>Employees working hours for the period from <%= @from%> to <%= @to%></h1>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Working hours</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>    
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <%x = employee.working_hours( Date.parse(params["locals"]["from"]), Date.parse(params["locals"]["to"]))%>
        <td><%= x[0]  %></td>
        <td><%= x[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Pay rate:</strong>
  <%= @employee.pay_rate %>
</p>

<p>
  <%# render :partial => "sign_list", :locals =>{:signs =>@employee.signs}  %>           
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/xcheck.html.erb
<h1>ckeck sign</h1>

<%= render 'form' %>

<%= link_to 'Back', signs_path %>

<div class="center">
  <h1> Employees signing for: <%= Time.now.strftime("%m-%d-%y ")%> </h1>
<table>
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>In</th>
      <th>Out</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.full_name %></td>
        <td><%= link_to 'check in', new_sign_path(employee) %></td>
        <td><%= link_to 'check out', edit_sign_path(employee) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmartSign</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/employees.html.erb
<DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>Emplyees: <%=controller.action_name%></title>
  <%=stylesheet_link_tag 'default.css'%>
</head>
  
<body>
  <div id="wrapper">
    <div id="header">
      <div>
        <h1>SmartSign</h1>
        <ul id="nav">
          <li><a href="/employees/">Edit Employees</a></li>
          <li><a href="/generat_payroll/">Payroll Report</a></li>
          <li><a href="/new_sign">Sign</a></li>
        </ul>
     </div>
   </div> 
    <div id="content">
      <%=yield%>
    </div>
    
    <div id="clearfooter"></div>
  </div>
    <div id="footer"></div>
</body>
</html>

app/views/layouts/signs.html.erb
<DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>Signs: <%=controller.action_name%></title>
  <%=stylesheet_link_tag 'default.css'%>
</head>
  
<body>
  <div id="wrapper">
    <div id="header">
      <div>
        <h1>SmartSign</h1>
        <ul id="nav">
          <li><a href="/employees/">Employees</a></li>
          <li><a href="/generat_payroll/">Payroll Report</a></li>
          <li><a href="/new_sign">Sign</a></li>
        </ul>
     </div>
   </div> 
    <div id="content">
      <%=yield%>
    </div>
    
    <div id="clearfooter"></div>
  </div>
    <div id="footer"></div>
</body>
</html>

app/views/signs/_form.html.erb
<div class="center">
<%= form_for(@sign) do |f| %>
  <% if @sign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign.errors.count, "error") %> prohibited this sign from being saved:</h2>

      <ul>
      <% @sign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "employee name" %><br>
    <%= f.select("employee_id", Employee.all.collect {|e| [e.full_name, e.id] }, {include_blank: true}) %>
  </div>
  <br>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <br>
  <div class="field">
    <%= f.label :check_in %><br>
    <%= f.time_select("check_in", ampm: true) %>
  </div>
  <br>
  <div class="field">
    <%= f.label :check_out %><br>
    <%= f.time_select("check_out", ampm: true) %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>
</div>

app/views/signs/edit.html.erb
<h1>Editing sign</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign %> |
<%= link_to 'Back', signs_path %>

app/views/signs/index.html.erb
<h1>Listing signs</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Date</th>
      <th>Check in</th>
      <th>Check out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signs.each do |sign| %>
      <tr>
        <td><%= sign.employee_id %></td>
        <td><%= sign.date %></td>
        <td><%= sign.check_in.strftime("%I:%M %p") %></td>
        <td><%= sign.check_out.strftime("%I:%M %p") %></td>
        <td><%= link_to 'Show', sign %></td>
        <td><%= link_to 'Edit', edit_sign_path(sign) %></td>
        <td><%= link_to 'Destroy', sign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign', new_sign_path %>

app/views/signs/new.html.erb
<h1>New sign</h1>

<%= render 'form_check' %>

<%= link_to 'Back', signs_path %>

app/views/signs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Employee:</strong>
  <%= @sign.employee_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @sign.date %>
</p>

<p>
  <strong>Check in:</strong>
  <%= @sign.check_in.strftime("%I:%M %p") %>
</p>

<p>
  <strong>Check out:</strong>
  <% if @sign.check_out != nil %>
  <%= @sign.check_out.strftime("%I:%M %p") %>
  <% end %>
</p>

<%= link_to 'Edit', edit_sign_path(@sign) %> |
<%= link_to 'Back', signs_path %>